spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: microservice-config-client-dev
server:
  port: 4444    
---
spring:
  profiles: test
  application:
    name: microservice-config-client-test
server:
  port: 4441    
