spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: microservice-config-client-dev
    abc:ddd
---
spring:
  profiles: test
  application:
    name: microservice-config-client-test
    abc:aaa